[build]
  publish = "."

# Ensure that .html extensions can be omitted cleanly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
